# Generated by Django 4.2.1 on 2023-06-22 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_banque', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CLientNNI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NNI', models.DecimalField(decimal_places=0, max_digits=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nni', models.CharField(max_length=10)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=16, unique=True)),
                ('role', models.CharField(choices=[('Client', 'Client'), ('AdminBanque', 'AdminBanque')], default='AdminBanque', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
                ('restricted', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_client', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('MyApp.user',),
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_emprunt', models.PositiveIntegerField(verbose_name='montant_emprunt')),
                ('Interet', models.PositiveIntegerField(verbose_name="Taux d'intérêt (%)")),
                ('duree_emprunt', models.PositiveIntegerField(verbose_name='Durée (mois)')),
                ('mensualite', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('benefice_banque', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('banque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.banque')),
            ],
        ),
        migrations.CreateModel(
            name='ClientBanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NNI', models.DecimalField(decimal_places=0, max_digits=10)),
                ('num_compte', models.CharField(max_length=10, unique=True)),
                ('banque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.banque')),
            ],
        ),
        migrations.CreateModel(
            name='DemandePret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('attente', 'En attente'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée')], default='attente', max_length=10)),
                ('num_telephone', models.PositiveIntegerField()),
                ('numero_compt', models.CharField(max_length=10)),
                ('mensualite', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True)),
                ('duree_emprunt', models.PositiveIntegerField(blank=True, null=True)),
                ('montant_emprunt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Salaire', models.DecimalField(decimal_places=0, max_digits=10)),
                ('cni', models.FileField(upload_to='static/cni/')),
                ('demande', models.FileField(upload_to='static/demande/')),
                ('contrat_de_travail', models.FileField(upload_to='static/contrats_de_travail/')),
                ('attestation_travail', models.FileField(upload_to='static/attestations_travail/')),
                ('justification_adresse', models.FileField(upload_to='static/justifications_adresse/')),
                ('bulletins_de_salaire', models.FileField(upload_to='static/bulletins_de_salaire/')),
                ('montant_total', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('banque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyApp.banque')),
                ('offre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyApp.offers')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.client')),
            ],
        ),
        migrations.CreateModel(
            name='AdminBanque',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_admin', models.BooleanField(default=True)),
                ('banque', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MyApp.banque')),
            ],
            options={
                'abstract': False,
            },
            bases=('MyApp.user',),
        ),
    ]
