# Generated by Django 4.2.1 on 2023-06-09 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_user_is_admin_user_is_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banque',
            old_name='AdminBanque',
            new_name='user',
        ),
    ]
