# Generated by Django 4.2.1 on 2023-06-09 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_rename_adminbanque_banque_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandepret',
            name='numero_compt',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
