# Generated by Django 4.2.1 on 2023-06-09 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_demandepret_numero_compt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandepret',
            name='raison',
        ),
    ]
