# Generated by Django 4.2.1 on 2023-06-09 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_remove_demandepret_raison'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banque',
            old_name='user',
            new_name='responsable_banque',
        ),
    ]
