# Generated by Django 4.2.1 on 2023-06-15 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_client_nni_alter_client_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='client_NNI',
        ),
    ]
