# Generated by Django 4.2.1 on 2023-06-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0012_client_banque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='num_telephone',
            field=models.PositiveIntegerField(),
        ),
    ]
