# Generated by Django 4.2.1 on 2023-06-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0013_alter_client_num_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banque',
            name='num_telephone',
            field=models.PositiveIntegerField(),
        ),
    ]
