# Generated by Django 4.2.1 on 2023-06-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0014_alter_banque_num_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandepret',
            name='mensualite',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True),
        ),
    ]
