# Generated by Django 4.2.1 on 2023-06-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0015_demandepret_mensualite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandepret',
            name='Salaire',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
