# Generated by Django 4.2.1 on 2023-06-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0016_alter_demandepret_salaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandepret',
            name='num_telephone',
            field=models.PositiveIntegerField(),
        ),
    ]
