# Generated by Django 4.2.1 on 2023-06-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0017_alter_demandepret_num_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandepret',
            name='montant_total',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
    ]
