# Generated by Django 4.2.1 on 2023-06-21 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0018_demandepret_montant_total'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='client_banque',
            new_name='ClientBanque',
        ),
        migrations.RenameModel(
            old_name='client_nni',
            new_name='CLientNNI',
        ),
    ]
