# Generated by Django 4.2.1 on 2023-06-21 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0019_rename_client_banque_clientbanque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbanque',
            name='banque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.banque'),
        ),
    ]
