# Generated by Django 4.2.1 on 2023-06-21 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0020_alter_clientbanque_banque'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientBanque',
        ),
    ]
